// <auto-generated />
using System;
using BeastKeeper.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeastKeeper.Web.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    [Migration("20190321204343_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("BeastKeeper.Core.Models.Beast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("Id");

                    b.ToTable("Beasts");
                });

            modelBuilder.Entity("BeastKeeper.Core.Models.HistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BeastId");

                    b.Property<string>("Description");

                    b.Property<string>("MedicalCode");

                    b.Property<DateTime>("ProcedureDate");

                    b.HasKey("Id");

                    b.HasIndex("BeastId");

                    b.ToTable("HistoryItems");
                });

            modelBuilder.Entity("BeastKeeper.Core.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BeastId");

                    b.Property<string>("Description");

                    b.Property<string>("ImgName");

                    b.Property<string>("ImgSource");

                    b.HasKey("Id");

                    b.HasIndex("BeastId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BeastKeeper.Core.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BeastId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<DateTime>("DueDate");

                    b.HasKey("Id");

                    b.HasIndex("BeastId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("BeastKeeper.Core.Models.HistoryItem", b =>
                {
                    b.HasOne("BeastKeeper.Core.Models.Beast", "Beast")
                        .WithMany("HistoryItems")
                        .HasForeignKey("BeastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeastKeeper.Core.Models.Photo", b =>
                {
                    b.HasOne("BeastKeeper.Core.Models.Beast", "Beast")
                        .WithMany("Photos")
                        .HasForeignKey("BeastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeastKeeper.Core.Models.Reminder", b =>
                {
                    b.HasOne("BeastKeeper.Core.Models.Beast", "Beast")
                        .WithMany("Reminders")
                        .HasForeignKey("BeastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
